query PaginatedBillings(
	$limit: Int = 10
	$offset: Int = 0
	$orderByField: String
	$orderDirection: String
) @auth(expr: "auth.token.role == 'admin'") {
	billingFromCsvs(
		limit: $limit
		orderBy: [{ mrSysNo: DESC }]
		offset: $offset
	) {
		id
		accountNo
		amortAmnt
		arrearsAmnt
		arrearsEnv
		bStatus
		billAmnt
		billBrgy
		billDate
		billNo
		billPurok
		book
		classType
		curReading
		discount
		disconDate
		dueDate
		duePenalty
		environmentFee
		fullName
		mPenalty
		mrSysNo
		mtrNo
		nrWater
		paid
		paymentDate
		paymentReceipt
		paymentStatus
		preReading
		prevUsed
		prevUsed2
		prvBillDate
		prvDiscon
		prvDueDate
		purokCode
		stubOut
		totalBill
		verified
		waterUsage
		createdAt
		updatedAt
	}
}

query CountBillingFromCsv @auth(expr: "auth.token.role == 'admin'") {
	billingFromCsvs {
		_count
	}
}

query SearchBillingFromCsv($query: String, $limit: Int = 10)
@auth(expr: "auth.token.role == 'admin'") {
	billingFromCsvs_search(query: $query, limit: $limit) {
		accountNo
		amortAmnt
		arrearsAmnt
		arrearsEnv
		bStatus
		billAmnt
		billBrgy
		billDate
		billNo
		billPurok
		book
		classType
		curReading
		discount
		disconDate
		dueDate
		duePenalty
		environmentFee
		fullName
		mPenalty
		mrSysNo
		mtrNo
		nrWater
		paid
		paymentDate
		paymentReceipt
		paymentStatus
		preReading
		prevUsed
		prevUsed2
		prvBillDate
		prvDiscon
		prvDueDate
		purokCode
		stubOut
		totalBill
		verified
		waterUsage
		createdAt
		updatedAt
	}
}
