# input BillingFromCSV {
# 	billNo: Int!
# 	accountNo: String! # Assuming accountno from CSV is required
# 	billDate: Date!
# 	dueDate: Date!
# 	bStatus: String!
# 	mrSysNo: Int!
# 	duePenalty: Float!
# 	penalized: String!
# 	mPenalty: Float!
# 	discount: Float!
# 	paid: String!
# 	verified: String!
# 	billAmnt: Float!
# 	arrearsAmt: Float!
# 	mrrfDue: Float!
# 	waterUsage: Int!
# 	curReading: Int!
# 	disconDate: Date
# 	mtrNo: String!
# 	book: String! # Assuming book from CSV is required
# 	classType: String! # Assuming classtype from CSV is required
# 	fullName: String! # Assuming fullname from CSV is required
# 	preReading: Int!
# 	purokCode: String!
# 	billPurok: String!
# 	billBrgy: String!
# 	custNo: String! # Assuming custno from CSV is required
# 	prevUsed: Int!
# 	prevUsed2: Int!
# 	prvBillDate: String!
# 	prvDueDate: String!
# 	prvDiscon: String!
# 	stubOut: String!
# 	amortAmt: Float!
# 	nrWater: Int!
# 	arrearsEnv: Float!
# }

mutation CreateBook($name: String!)
@auth(expr: "auth.token.role == 'admin'")
@transaction {
	query {
		books(where: { name: { eq: $name } }) {
			id
		}
	}

	book_insert(data: { name: $name })
		@check(
			expr: "response.query.books.size() == 0"
			message: "Book already exists"
			optional: true
		)
}

mutation CreateResident(
	$accountNo: Int!
	$fullName: String!
	$classType: String!
	$bookId: UUID!
) @auth(expr: "auth.token.role == 'admin'") @transaction {
	query {
		residents(where: { accountNo: { eq: $accountNo } }) {
			id
		}
	}

	resident_insert(
		data: {
			accountNo: $accountNo
			fullName: $fullName
			classType: $classType
			bookId: $bookId
		}
	)
		@check(
			expr: "response.query.residents.size() == 0"
			message: "Resident already exists"
		)
}

mutation CreateBilling(
	$billNo: Int!
	$billDate: Date!
	$dueDate: Date!
	$bStatus: String!
	$mrSysNo: Int!
	$penalized: String!
	$mPenalty: Float!
	$discount: Float!
	$paid: String!
	$verified: String!
	$arrearsAmt: Float!
	$mrrfDue: Float!
	$curReading: Int!
	$disconDate: Date
	$mtrNo: String!
	$preReading: Int!
	$purokCode: String!
	$billPurok: String!
	$billBrgy: String!
	$prevUsed: Int!
	$prevUsed2: Int!
	$prvBillDate: String!
	$prvDueDate: String!
	$prvDiscon: String!
	$stubOut: String!
	$amortAmt: Float!
	$nrWater: Int!
	$residentId: UUID! # Assuming Resident has a Key type
	$bookId: UUID! # Assuming Book has a Key type
	$billAmt: Float!
	$duePenalty: Float!
	$arrearsEnv: Float!
	$environmentFee: Float!
	$totalBill: Float!
	$waterUsage: Int!
	$paymentReceipt: String
	$paymentStatus: String
	$paymentDate: Date
) @auth(expr: "auth.token.role == 'admin'") {
	billing_insert(
		data: {
			billNo: $billNo
			billDate: $billDate
			dueDate: $dueDate
			bStatus: $bStatus
			mrSysNo: $mrSysNo
			penalized: $penalized
			mPenalty: $mPenalty
			discount: $discount
			paid: $paid
			verified: $verified
			arrearsAmt: $arrearsAmt
			mrrfDue: $mrrfDue
			curReading: $curReading
			disconDate: $disconDate
			mtrNo: $mtrNo
			preReading: $preReading
			purokCode: $purokCode
			billPurok: $billPurok
			billBrgy: $billBrgy
			prevUsed: $prevUsed
			prevUsed2: $prevUsed2
			prvBillDate: $prvBillDate
			prvDueDate: $prvDueDate
			prvDiscon: $prvDiscon
			stubOut: $stubOut
			amortAmt: $amortAmt
			nrWater: $nrWater
			residentId: $residentId
			bookId: $bookId
			billAmt: $billAmt
			duePenalty: $duePenalty
			arrearsEnv: $arrearsEnv
			environmentFee: $environmentFee
			totalBill: $totalBill
			waterUsage: $waterUsage
			paymentReceipt: $paymentReceipt
			paymentStatus: $paymentStatus
			paymentDate: $paymentDate
		}
	)
}

mutation CreateBillingFromCsv(
	$accountNo: String!
	$amortAmnt: Float!
	$arrearsAmnt: Float!
	$arrearsEnv: Float!
	$bStatus: String!
	$billAmnt: Float!
	$billBrgy: String
	$billDate: String!
	$billNo: String!
	$billPurok: String
	$book: String!
	$classType: String!
	$curReading: Int!
	$custNo: Int!
	$discount: Float!
	$disconDate: String!
	$dueDate: String!
	$duePenalty: Float!
	$environmentFee: Float!
	$fullName: String!
	$mPenalty: Float!
	$mrrfDue: Float!
	$mrSysNo: Int!
	$mtrNo: String!
	$nrWater: Float!
	$paid: String!
	$paymentDate: String
	$paymentReceipt: String
	$paymentStatus: String
	$penalized: Int!
	$preReading: Int!
	$prevUsed: Float!
	$prevUsed2: Float!
	$prvBillDate: String!
	$prvDiscon: String!
	$prvDueDate: String!
	$purokCode: String
	$stubOut: String
	$totalBill: Float!
	$verified: String!
	$waterUsage: Float!
) @auth(expr: "auth.token.role == 'admin'") {
	billingFromCsv_insert(
		data: {
			accountNo: $accountNo
			amortAmnt: $amortAmnt
			arrearsAmnt: $arrearsAmnt
			arrearsEnv: $arrearsEnv
			bStatus: $bStatus
			billAmnt: $billAmnt
			billBrgy: $billBrgy
			billDate: $billDate
			billNo: $billNo
			billPurok: $billPurok
			book: $book
			classType: $classType
			curReading: $curReading
			discount: $discount
			disconDate: $disconDate
			dueDate: $dueDate
			duePenalty: $duePenalty
			environmentFee: $environmentFee
			fullName: $fullName
			mPenalty: $mPenalty
			mrSysNo: $mrSysNo
			mtrNo: $mtrNo
			nrWater: $nrWater
			paid: $paid
			paymentDate: $paymentDate
			paymentReceipt: $paymentReceipt
			paymentStatus: $paymentStatus
			preReading: $preReading
			prevUsed: $prevUsed
			prevUsed2: $prevUsed2
			prvBillDate: $prvBillDate
			prvDiscon: $prvDiscon
			prvDueDate: $prvDueDate
			purokCode: $purokCode
			stubOut: $stubOut
			totalBill: $totalBill
			verified: $verified
			waterUsage: $waterUsage
		}
	)
}

mutation DeleteBillingFromCsv($id: UUID!)
@auth(expr: "auth.token.role == 'admin'") {
	billingFromCsv_delete(id: $id)
}

mutation UpdateBillingFromCsv(
	$id: UUID!
	$accountNo: String
	$amortAmnt: Float
	$arrearsAmnt: Float
	$arrearsEnv: Float
	$bStatus: String
	$billAmnt: Float
	$billBrgy: String
	$billDate: String
	$billNo: String
	$billPurok: String
	$book: String
	$classType: String
	$curReading: Int
	$custNo: Int
	$discount: Float
	$disconDate: String
	$dueDate: String
	$duePenalty: Float
	$environmentFee: Float
	$fullName: String
	$mPenalty: Float
	$mrrfDue: Float
	$mrSysNo: Int
	$mtrNo: String
	$nrWater: Float
	$paid: String
	$paymentDate: String
	$paymentReceipt: String
	$paymentStatus: String
	$penalized: Int
	$preReading: Int
	$prevUsed: Float
	$prevUsed2: Float
	$prvBillDate: String
	$prvDiscon: String
	$prvDueDate: String
	$purokCode: String
	$stubOut: String
	$totalBill: Float
	$verified: String
	$waterUsage: Float
) @auth(expr: "auth.token.role == 'admin'") {
	billingFromCsv_update(
		id: $id
		data: {
			accountNo: $accountNo
			amortAmnt: $amortAmnt
			arrearsAmnt: $arrearsAmnt
			arrearsEnv: $arrearsEnv
			bStatus: $bStatus
			billAmnt: $billAmnt
			billBrgy: $billBrgy
			billDate: $billDate
			billNo: $billNo
			billPurok: $billPurok
			book: $book
			classType: $classType
			curReading: $curReading
			discount: $discount
			disconDate: $disconDate
			dueDate: $dueDate
			duePenalty: $duePenalty
			environmentFee: $environmentFee
			fullName: $fullName
			mPenalty: $mPenalty
			mrSysNo: $mrSysNo
			mtrNo: $mtrNo
			nrWater: $nrWater
			paid: $paid
			paymentDate: $paymentDate
			paymentReceipt: $paymentReceipt
			paymentStatus: $paymentStatus
			preReading: $preReading
			prevUsed: $prevUsed
			prevUsed2: $prevUsed2
			prvBillDate: $prvBillDate
			prvDiscon: $prvDiscon
			prvDueDate: $prvDueDate
			purokCode: $purokCode
			stubOut: $stubOut
			totalBill: $totalBill
			verified: $verified
			waterUsage: $waterUsage
		}
	)
}
