mutation InsertBook($data: Book_Data!) {
	book_insert(data: $data)
}

mutation InsertResident($data: Resident_Data!) {
	resident_insert(data: $data)
}

mutation InsertBilling($data: Billing_Data!) {
	billing_insert(data: $data)
}
