query PaginatedBillings($limit: Int = 10, $offset: Int = 0)
@auth(expr: "auth.token.role == 'admin'") {
  billingFromCsvs(limit: $limit, orderBy: [{ billNo: DESC }], offset: $offset) {
    accountNo
    amortAmnt
    arrearsAmnt
    arrearsEnv
    bStatus
    billAmnt
    billBrgy
    billDate
    billNo
    billPurok
    book
    classType
    curReading
    discount
    disconDate
    dueDate
    duePenalty
    environmentFee
    fullName
    mPenalty
    mrSysNo
    mtrNo
    nrWater
    paid
    paymentDate
    paymentReceipt
    paymentStatus
    preReading
    prevUsed
    prevUsed2
    prvBillDate
    prvDiscon
    prvDueDate
    purokCode
    residentId
    stubOut
    totalBill
    verified
    waterUsage
    createdAt
    updatedAt
  }
}

query GetBooks @auth(level: PUBLIC) {
	books {
		id
		name
	}
}

query GetBookByName($name: String!) @auth(level: PUBLIC) {
	books(where: { name: { eq: $name } }) {
		id
	}
}

query GetResidentByAccountNo($accountNo: Int!)
@auth(expr: "(auth.token.role == 'admin') || (auth != null)") {
	residents(where: { accountNo: { eq: $accountNo } }) {
		id
	}
}

query GetResidents @auth(expr: "auth.token.role == 'admin'") {
	residents {
		id
		accountNo
		fullName
		classType
		book {
			name
		}
	}
}
