query GetSurveys @auth(expr: "auth.token.role == 'admin'") {
	surveys {
		id
		title
		description
		status
		responsesCount
		createdAt
	}
}

query GetSurveyById($id: UUID!) @auth(level: USER) {
	survey(id: $id) {
		id
		title
		description
		status
		responsesCount
		createdAt
	}
}
