# This is a file for you to write an un-named mutation.
# Only one un-named mutation is allowed per file.
mutation {
	resident_insert(
		data: {
			id: "11111111222233334444555555555555"
			bookId: "11111111222233334444555555555555"
			classType: "RESIDENTIAL"
			createdAt: "2025-10-24T16:29:07.219Z"
			fullName: "all peter"
			notificationToken: ""
		}
	)
}
