
# This is a file for you to write an un-named query.
# Only one un-named query is allowed per file.
query {
  residents{
    fullName
    book {
      code
      updatedAt
    }
    classType
    notificationToken
    createdAt
  }
}