type CollectionFromCsv @table {
	accountNo: String! # e.g 0611202177
	amortize: Float # e.g 0.00
	arrearsAmt: Float # e.g 0.00
	arrearsEnv: Float # e.g 0.00
	bankGroup: Int # e.g 0
	bankId: String # e.g POS
	bankOnline: Float # e.g 0.00
	batchNo: String # e.g (empty)
	billNo: String # e.g (empty)
	branch: String # e.g (empty)
	cash: Float! # e.g 712.25
	check: Float! # e.g 0.00
	checkDate: String # e.g /  /
	checkNo: String # e.g (empty)
	cmrrfAmnt: Float! # e.g 13.25
	custNo: Int! # e.g 2177
	discAmnt: Float! # e.g 0.00
	envFee: Float! # e.g 13.25
	fullName: String! # e.g JABAYBAY, MARIVIC - II
	mrrfAmnt: Float! # e.g 0.00
	onlineref: String # e.g (empty)
	othrApply: Float # e.g 0.00
	othrIncome: Float # e.g 0.00
	othrReconn: Float # e.g 0.00
	pacyAmnt: Float! # e.g 699.00
	papYAmnt: Float! # e.g 0.00
	payArrears: Boolean! # e.g F (false)
	penAmnt: Float! # e.g 0.00
	pymtDate: String! # e.g 01/03/2025
	pymtMethod: Int! # e.g 1
	receiptNo: String! @unique # e.g 6994384
	receiptStatus: String! # e.g 01
	receiptType: String! # e.g 04
	runBalance: Float # e.g 0.00
	sysNo: Int! @unique # e.g 36748
	teller: String! # e.g CESAR
	trackDt: String! # e.g 01/03/2025 07:57:06
	waterBill: Float! # e.g 699.00
}
